export const initialValues = {
    axis: 'y',
    widthFirefox: 'auto',
    thickness: 18,
    isTrackTransparent: false,
    trackBg: '#e7e7e7',
    trackBgHover: '#cfcfcf',
    trackRadius: 8,
    trackBorderWidth: 1,
    trackBorderStyle: 'solid',
    trackBorderColor: '#cacaca',
    thumbBg: '#d55959',
    thumbBgHover: '#cf3f3f',
    thumbRadius: 50,
}
